# Generated by Django 3.1.5 on 2021-01-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerseStudyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=512)),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
        ),
    ]
