# Generated by Django 3.1.5 on 2021-01-26 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTheVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(help_text='Beware this date (UTC) is adjusted to CT upon calculation (-6) whether stat is in range of last sun 00:00 to last sat 23:59.')),
                ('stat_time_secs', models.PositiveIntegerField()),
                ('stat_grade_level', models.IntegerField()),
                ('stat_total_correct', models.PositiveIntegerField()),
                ('stat_total_questions', models.PositiveIntegerField()),
                ('stat_stars', models.PositiveIntegerField()),
                ('stat_score', models.PositiveIntegerField()),
                ('current_best', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complete The Verse',
                'verbose_name_plural': 'Complete The Verse',
            },
        ),
    ]
