# Generated by Django 3.1.5 on 2021-02-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_church_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='meeting_date',
            field=models.DateField(),
        ),
    ]
