# Generated by Django 3.1.5 on 2021-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210211_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200, null=True)),
                ('prayer', models.CharField(max_length=20000)),
                ('datestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-datestamp'],
                'unique_together': {('person', 'prayer')},
            },
        ),
    ]
