# Generated by Django 3.1.5 on 2021-02-15 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210215_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
