# Generated by Django 3.1.5 on 2021-02-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210215_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
