# Generated by Django 3.1.5 on 2021-02-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210216_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_registration', to='main.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_attendance', to='main.registration')),
            ],
            options={
                'ordering': ['-attendance_date'],
                'unique_together': {('attendance_date',)},
            },
        ),
    ]
