# Generated by Django 3.1.5 on 2021-02-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_attendance_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='registration',
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='main.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to='main.user'),
            preserve_default=False,
        ),
    ]
