# Generated by Django 3.1.5 on 2021-02-16 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210216_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
