# Generated by Django 3.1.5 on 2021-02-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_prayerrequest_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('attendance_date', 'student', 'course')},
        ),
    ]
