# Generated by Django 3.1.5 on 2021-02-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210224_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='church_logos/'),
        ),
    ]
