# Generated by Django 3.1.5 on 2021-02-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_church_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='fund_tag',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='user_allowed',
        ),
        migrations.AddField(
            model_name='accounts',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_church', to='main.church'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
