# Generated by Django 3.1.5 on 2021-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210226_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
