# Generated by Django 3.1.5 on 2021-02-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210226_0152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funds',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
