# Generated by Django 3.1.5 on 2021-02-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210226_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='logo',
        ),
    ]
