# Generated by Django 3.1.5 on 2021-02-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210228_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='state_abbrev',
            field=models.CharField(max_length=30),
        ),
    ]
