# Generated by Django 3.1.5 on 2021-03-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210228_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('fund', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_type', models.CharField(choices=[('One-Time', 'One-Time'), ('Monthly', 'Monthly')], max_length=50)),
                ('agreement', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('chruch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_church', to='main.church')),
            ],
        ),
    ]
