# Generated by Django 3.1.5 on 2021-03-06 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
