# Generated by Django 3.1.5 on 2021-03-06 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210306_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
