# Generated by Django 3.1.5 on 2021-03-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210306_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
