# Generated by Django 3.1.5 on 2021-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_church_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
