# Generated by Django 3.1.5 on 2021-03-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210307_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=250)),
                ('routing_number', models.CharField(max_length=250)),
                ('account_holder_name', models.CharField(max_length=250)),
                ('chruch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_bank_details', to='main.church')),
            ],
            options={
                'verbose_name_plural': 'Bank_Details',
            },
        ),
    ]
