# Generated by Django 3.1.5 on 2021-03-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='is_bank_verified',
            field=models.BooleanField(default=False),
        ),
    ]
