from django.contrib import admin
from django.conf.urls import url
from django.urls import path, re_path, include
from django.conf.urls import handler404, handler500


from main.views import (
    administrator_attendance_list_view,
    accounts_create_view,
    accounts_list_view,
    accounts_detail_page,
    accounts_delete_view,
    accounts_update_view,
    accounting_information,
    attendance_list_view,
    attendance_detail_page,
    attendance_delete_view,
    attendance_update_view,
    attendance_create_view,
    attendance_report_date_view,  
    attendance_report_event_view,
    attendance_report_student_view,
    attendance_information,
    record_attendance_choose_course_view,
    record_attendance_view,
    check_in_view,
    church_list_view,
    church_detail_page,
    church_delete_view,
    church_update_view,
    church_create_view,
    contribution_information,
    course_create_view,
    course_list_view,
    course_delete_view,
    course_detail_page,
    course_update_view,
    course_information,
    home_page,
    member_create_view,
    member_list_view,
    download_member_list,
    member_information,
    minutes_list_view,
    minutes_detail_page,
    minutes_delete_view,
    minutes_update_view,
    minutes_create_view,
    minutes_information,
    activate_prayer_circle,
    prayer_request_create_view,
    prayer_request_list_view,
    prayer_delete_view,
    prayer_update_view,
    prayer_request_anon_create_view,
    register_for_an_event_view,
    registration_delete_view,
    registration_schedule_view,
    registration_admin_schedule_view,
    request_account_view,
    request_church_account_view,
    send_email_to_members,
    user_login,
    user_logout,    
    user_delete_view,
    user_update_view,
    user_list_view,    
    user_create_view,
    user_upload,
    download_user_list,
    contributions_enter,
    ShopView,
    charge_amount_payment,
    add_payment_details,
    add_bank_details,
    church_contribution_view,
    identity_verification,
)

urlpatterns = [
    path("", home_page), 
    path('admin/', admin.site.urls),
    path("accounts/", accounts_list_view),
    path("accounts/<int:id>/", accounts_detail_page),    
    path("accounts/<int:id>/delete/", accounts_delete_view),
    path("accounts/<int:id>/update/", accounts_update_view),
    path("accounts-create/", accounts_create_view),    
    path("accounting-information/", accounting_information),
    path("attendance-info/", attendance_information),
    path("attendance/", attendance_list_view),
    path("attendance-all/", administrator_attendance_list_view),
    path("attendance/<int:id>/", attendance_detail_page),    
    path("attendance/<int:id>/delete", attendance_delete_view),
    path("attendance/<int:id>/update/", attendance_update_view),
    path("attendance-create/", attendance_create_view),
    path("attendance-report-date/", attendance_report_date_view),
    path("attendance-report-event/", attendance_report_event_view),
    path("attendance-record/", record_attendance_choose_course_view),
    path("attendance-record/<int:course_id>/", record_attendance_view),
    path("attendance-report-student/", attendance_report_student_view),
    path("check-in/", check_in_view),
    path("church/", church_list_view),
    path("church/<int:id>/", church_detail_page),    
    path("church/<int:id>/delete", church_delete_view),
    path("church/<int:id>/update/", church_update_view),
    path("church-create/", church_create_view),
    path("contribution-information/", contribution_information),
    path('contact-members/', send_email_to_members),     
    path("events/<int:id>/delete", course_delete_view),
    path('events-create/', course_create_view), 
    path("events/<int:id>/update/", course_update_view),
    path("events/<int:id>/", course_detail_page),
    path("events-information/", course_information),
    path('events/', course_list_view),
    path('login/', user_login),
    path('logout/', user_logout),
    path("members/", member_list_view),    
    path("members-create/", member_create_view),
    path("download-members/", download_member_list),
    path("member-information/", member_information),
    path("minutes/", minutes_list_view),
    path("minutes/<int:id>/", minutes_detail_page),    
    path("minutes/<int:id>/delete/", minutes_delete_view),
    path("minutes/<int:id>/update/", minutes_update_view),
    path("minutes-create/", minutes_create_view),
    path("minutes-information/", minutes_information),
    path("prayer-circle/", activate_prayer_circle),
    path("prayer/", prayer_request_list_view),
    path("prayer-request/", prayer_request_create_view),
    path("anon-request-prayer/", prayer_request_anon_create_view),
    path("prayer/<int:id>/delete/", prayer_delete_view),
    path("prayer/<int:id>/update/", prayer_update_view),
    path("register/", register_for_an_event_view),
    path("registration/<int:id>/delete/", registration_delete_view),
    path("registration/", registration_schedule_view),
    path("registration-admin/", registration_admin_schedule_view),
    path("request-account/", request_account_view),
    path("request-church-account/", request_church_account_view),
    path("study/", include('study.urls')), 
    path("user/<int:id>/delete/", user_delete_view),
    path("user/<int:id>/update/", user_update_view),
    path("users/", user_list_view),    
    path("user-create/", user_create_view),
    path("user-upload/", user_upload),
    path("download-users/", download_user_list),
    path("contributions-enter/", contributions_enter),
    path("stripe/", ShopView.as_view()),
    path("stripe-payment/", charge_amount_payment),
    path("add-payment-details/<int:id>", add_payment_details,name="add-payment-details"),
    path("add-bank-details/<int:id>", add_bank_details,name="add-bank-details"),
    path("contributions-account/", church_contribution_view,name="church_contribution_view"),
    path("identity-verification/", identity_verification,name="identity-verification"),
]
